### ISSUE TITLE
Inflating Error

### ISSUE THREAD

**Issue by nicemak** [iammert/MultiSearchView#10]
i got this error after implementing this.

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: pk.com.informatica.tkonnect, PID: 23427
    java.lang.RuntimeException: Unable to start activity ComponentInfo{pk.com.informatica.tkonnect/pk.com.informatica.tkonnect.ui.home.MainActivity}: android.view.InflateException: Binary XML file line #15 in pk.com.informatica.tkonnect:layout/activity_main: Binary XML file line #166 in pk.com.informatica.tkonnect:layout/content_main: Error inflating class com.iammert.library.ui.multisearchviewlib.MultiSearchView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3304)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3443)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: android.view.InflateException: Binary XML file line #15 in pk.com.informatica.tkonnect:layout/activity_main: Binary XML file line #166 in pk.com.informatica.tkonnect:layout/content_main: Error inflating class com.iammert.library.ui.multisearchviewlib.MultiSearchView
     Caused by: android.view.InflateException: Binary XML file line #166 in pk.com.informatica.tkonnect:layout/content_main: Error inflating class com.iammert.library.ui.multisearchviewlib.MultiSearchView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1267)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1267)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
        at pk.com.informatica.tkonnect.ui.home.MainActivity.onCreate(MainActivity.kt:72)
        at android.app.Activity.performCreate(Activity.java:7893)
        at android.app.Activity.performCreate(Activity.java:7880)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3279)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3443)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/AndroidRuntime:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/databinding/DataBinderMapperImpl;
        at androidx.databinding.DataBindingUtil.<clinit>(DataBindingUtil.java:32)
        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:95)
        at com.iammert.library.ui.multisearchviewlib.extensions.DataBindingExtensionsKt.inflate(DataBindingExtensions.kt:17)
        at com.iammert.library.ui.multisearchviewlib.extensions.DataBindingExtensionsKt.inflate$default(DataBindingExtensions.kt:16)
        at com.iammert.library.ui.multisearchviewlib.MultiSearchView.<init>(MultiSearchView.kt:23)
        at com.iammert.library.ui.multisearchviewlib.MultiSearchView.<init>(MultiSearchView.kt:9)
        at com.iammert.library.ui.multisearchviewlib.MultiSearchView.<init>(Unknown Source:6)
        	... 38 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.databinding.DataBinderMapperImpl" on path: DexPathList[[zip file "/data/app/pk.com.informatica.tkonnect-97ae8aK8Zl_QasSvSudVhw==/base.apk"],nativeLibraryDirectories=[/data/app/pk.com.informatica.tkonnect-97ae8aK8Zl_QasSvSudVhw==/lib/arm64, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 45 more`

**Comment by mertceyhan** [comment]
Could you try again with the new release? @nicemak

**Comment by nicemak** [comment]
ok i will update you on this soon!

**Comment by omarabubakrll** [comment]
android {
 buildFeatures {
        dataBinding true
    }
}

Put this In-app Gradle file
Enjoy!

**Comment by yamin8000** [comment]
> 
> 
> android {
> buildFeatures {
> dataBinding true
> }
> }
> 
> Put this In-app Gradle file
> Enjoy!

What if I don't want to use or enable data binding?
