### ISSUE TITLE
Random Error - parameter must be a descendant of this view

### ISSUE THREAD

**Issue by DennyWeinberg** [iammert/MultiSearchView#7]
When clicking on the search icon (copen, close, open, close, ...), I randomly get the following error:
```
2020-03-22 21:18:39.640 7533-7533/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.levionsoftware.instagram_map, PID: 7533
    java.lang.IllegalArgumentException: parameter must be a descendant of this view
        at android.view.ViewGroup.offsetRectBetweenParentAndChild(ViewGroup.java:6414)
        at android.view.ViewGroup.offsetDescendantRectToMyCoords(ViewGroup.java:6336)
        at android.widget.HorizontalScrollView.isWithinDeltaOfScreen(HorizontalScrollView.java:1724)
        at android.widget.HorizontalScrollView.onSizeChanged(HorizontalScrollView.java:2125)
        at android.view.View.sizeChange(View.java:23911)
        at android.view.View.setBottom(View.java:17998)
        at android.animation.PropertyValuesHolder.nCallIntMethod(Native Method)
        at android.animation.PropertyValuesHolder.access$200(PropertyValuesHolder.java:38)
        at android.animation.PropertyValuesHolder$IntPropertyValuesHolder.setAnimatedValue(PropertyValuesHolder.java:1240)
        at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:990)
        at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1349)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1481)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:994)
        at android.view.Choreographer.doCallbacks(Choreographer.java:794)
        at android.view.Choreographer.doFrame(Choreographer.java:725)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7777)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

```

GIF:
https://imgur.com/VaUivgR

**Comment by grayhatdevelopers** [comment]
Same issue here

**Comment by mertceyhan** [comment]
Could you try again with new release? @DennyWeinberg @grayhatdevelopers
